spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
      name: cmmi
      url: jdbc:mysql://47.100.42.91:3388/newcloud?rewriteBatchedStatements=true
      username: root
      password: turing123
      maxActive: 20
      initialSize: 5
      maxWait: 12000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 12000
      testOnBorrow: false
      validationQuery: select 1
      filters: wall,stat
      removeAbandoned: true
      removeAbandonedTimeout: 300
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8
    multipart:
      location: E:/upload/tmp
      maxFileSize: 52428800
      maxRequestSize: 52428800
      
  thymeleaf:
    prefix:
      "classpath:templates/"
    check-template-location:
      true
    suffix:
      .html
    encoding:
      UTF-8
    content-type:
      text/html
    mode:
      HTML5
    cache:
      false

  redis:
      host: 47.100.42.91
      port: 6676
      database: 4
      #host: 127.0.0.1
      #port: 6379
      #password: turing123
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1
      timeout: 100000


debug: true
server:
  port: 52809
  tomcat:
    uri-encoding: utf-8
   


#打印SQL语句
logging:
  level:
    root: info
    com:
      turingmaker:
        dao:
          mapper:
            debug
        controll:
          config: debug